version: '3.9'
services:
  node-app:
    build: .
    container_name: server
    ports:
      - 3000:${PORT}
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      PORT: ${PORT}
    networks:
      - test
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql
    container_name: database
    restart: always
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:${MYSQL_PORT}'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
    networks:
      - test
volumes:
  db:
    driver: local
networks:
  test:
    driver: bridge