CREATE DATABASE IF NOT EXISTS companydb;
USE companydb;
CREATE TABLE IF NOT EXISTS employee(
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(32) NOT NULL,
  salary INT(1000) DEFAULT 0,
  PRIMARY KEY (id)
);
